import { Event, Banner, Ticket, StaffMember, PayoutRequest, Organizer, User } from "./types";
import { demoUsers } from "./auth-context";

export const mockEvents: Event[] = [
  {
    id: "evt-001",
    title: "Ghettocracy Comedy Night 2024",
    description: "Join us for an unforgettable night of laughter featuring Zimbabwe's finest comedians. Experience the raw, unfiltered humor that has made Ghettocracy a household name.",
    category: "comedy",
    date: "2024-12-15",
    time: "19:00",
    venue: "Harare International Conference Centre",
    city: "Harare",
    image: "/events/comedy-night.jpg",
    gallery: [],
    organizerId: "org-001",
    organizerName: "Ghettocracy Entertainment",
    ticketTypes: [
      { id: "tt-001", name: "Mbombera", description: "Standard seating", price: 15, currency: "USD", quantity: 500, sold: 420 },
      { id: "tt-002", name: "VIP", description: "Front row with meet & greet", price: 50, currency: "USD", quantity: 100, sold: 85 },
      { id: "tt-003", name: "VVIP", description: "Premium experience with dinner", price: 100, currency: "USD", quantity: 50, sold: 42 },
    ],
    totalTickets: 650,
    soldTickets: 547,
    status: "published",
    createdAt: "2024-10-01T10:00:00Z",
    updatedAt: "2024-11-15T14:30:00Z",
    platformMarkup: 5,
  },
  {
    id: "evt-002",
    title: "Harare Marathon 2024",
    description: "The biggest running event in Zimbabwe returns! Whether you're a seasoned runner or a first-timer, join thousands in this celebration of fitness and community.",
    category: "marathon",
    date: "2024-12-08",
    time: "06:00",
    venue: "National Sports Stadium",
    city: "Harare",
    image: "/events/marathon.jpg",
    gallery: [],
    organizerId: "org-002",
    organizerName: "Zimbabwe Athletics Association",
    ticketTypes: [
      { id: "tt-004", name: "5km Fun Run", description: "Family-friendly 5km route", price: 10, currency: "USD", quantity: 2000, sold: 1500 },
      { id: "tt-005", name: "10km Race", description: "Competitive 10km race", price: 20, currency: "USD", quantity: 1000, sold: 780 },
      { id: "tt-006", name: "Full Marathon", description: "42.2km full marathon", price: 35, currency: "USD", quantity: 500, sold: 320 },
    ],
    totalTickets: 3500,
    soldTickets: 2600,
    status: "published",
    createdAt: "2024-09-15T08:00:00Z",
    updatedAt: "2024-11-20T09:15:00Z",
  },
  {
    id: "evt-003",
    title: "Jah Prayzah Live in Concert",
    description: "The military touch general brings his electrifying performance to Harare. An evening of soulful Zimbabwean music that will leave you wanting more.",
    category: "music",
    date: "2024-12-22",
    time: "18:00",
    venue: "Borrowdale Racecourse",
    city: "Harare",
    image: "/events/concert.jpg",
    gallery: [],
    organizerId: "org-003",
    organizerName: "Military Touch Movement",
    ticketTypes: [
      { id: "tt-007", name: "General", description: "Standing area", price: 20, currency: "USD", quantity: 5000, sold: 3200 },
      { id: "tt-008", name: "Premium", description: "Reserved seating", price: 50, currency: "USD", quantity: 1000, sold: 650 },
      { id: "tt-009", name: "VIP Lounge", description: "Exclusive lounge access", price: 150, currency: "USD", quantity: 200, sold: 180 },
    ],
    totalTickets: 6200,
    soldTickets: 4030,
    status: "published",
    createdAt: "2024-10-20T12:00:00Z",
    updatedAt: "2024-11-18T16:45:00Z",
    platformMarkup: 10,
  },
  {
    id: "evt-004",
    title: "Tech Summit Zimbabwe 2024",
    description: "Connect with tech leaders, startups, and innovators. Explore the future of technology in Africa through keynotes, workshops, and networking sessions.",
    category: "conference",
    date: "2024-12-10",
    time: "08:00",
    venue: "Rainbow Towers Hotel",
    city: "Harare",
    image: "/events/tech-summit.jpg",
    gallery: [],
    organizerId: "org-004",
    organizerName: "ZimTech Foundation",
    ticketTypes: [
      { id: "tt-010", name: "Standard Pass", description: "Full conference access", price: 75, currency: "USD", quantity: 300, sold: 210 },
      { id: "tt-011", name: "Workshop Pass", description: "Conference + all workshops", price: 150, currency: "USD", quantity: 100, sold: 65 },
      { id: "tt-012", name: "VIP Pass", description: "All access + speakers dinner", price: 300, currency: "USD", quantity: 50, sold: 28 },
    ],
    totalTickets: 450,
    soldTickets: 303,
    status: "published",
    createdAt: "2024-08-01T09:00:00Z",
    updatedAt: "2024-11-22T11:30:00Z",
  },
  {
    id: "evt-005",
    title: "Bulawayo Arts Festival",
    description: "Celebrate the rich cultural heritage of Matabeleland through art, music, dance, and traditional cuisine. A three-day extravaganza of creativity.",
    category: "festival",
    date: "2024-12-27",
    time: "10:00",
    venue: "Large City Hall",
    city: "Bulawayo",
    image: "/events/arts-festival.jpg",
    gallery: [],
    organizerId: "org-005",
    organizerName: "Bulawayo Arts Council",
    ticketTypes: [
      { id: "tt-013", name: "Day Pass", description: "Single day access", price: 5, currency: "USD", quantity: 1000, sold: 450 },
      { id: "tt-014", name: "Weekend Pass", description: "All three days", price: 12, currency: "USD", quantity: 500, sold: 280 },
      { id: "tt-015", name: "Family Pack", description: "4 weekend passes", price: 40, currency: "USD", quantity: 200, sold: 95 },
    ],
    totalTickets: 1700,
    soldTickets: 825,
    status: "published",
    createdAt: "2024-10-10T14:00:00Z",
    updatedAt: "2024-11-25T10:00:00Z",
  },
  {
    id: "evt-006",
    title: "Stand-Up Comedy Showdown",
    description: "Who will be crowned Zimbabwe's funniest comedian? Watch as 10 comedians battle it out in this ultimate comedy competition.",
    category: "comedy",
    date: "2024-12-20",
    time: "20:00",
    venue: "Theatre in the Park",
    city: "Harare",
    image: "/events/comedy-showdown.jpg",
    gallery: [],
    organizerId: "org-006",
    organizerName: "Laugh Factory ZW",
    ticketTypes: [
      { id: "tt-016", name: "Standard", description: "General admission", price: 10, currency: "USD", quantity: 200, sold: 150 },
      { id: "tt-017", name: "Premium", description: "Best seats in the house", price: 25, currency: "USD", quantity: 50, sold: 40 },
    ],
    totalTickets: 250,
    soldTickets: 190,
    status: "published",
    createdAt: "2024-11-01T16:00:00Z",
    updatedAt: "2024-11-24T13:20:00Z",
  },
  {
    id: "evt-007",
    title: "Fitness Boot Camp",
    description: "Transform your body and mind with our intensive 2-day fitness boot camp. Expert trainers, nutritional guidance, and a supportive community.",
    category: "workshop",
    date: "2025-01-04",
    time: "05:30",
    venue: "Avondale Sports Club",
    city: "Harare",
    image: "/events/bootcamp.jpg",
    gallery: [],
    organizerId: "org-007",
    organizerName: "FitZim Academy",
    ticketTypes: [
      { id: "tt-018", name: "Individual", description: "Full boot camp access", price: 30, currency: "USD", quantity: 50, sold: 22 },
      { id: "tt-019", name: "Buddy Pack", description: "2 participants", price: 50, currency: "USD", quantity: 20, sold: 8 },
    ],
    totalTickets: 70,
    soldTickets: 30,
    status: "published",
    createdAt: "2024-11-10T07:00:00Z",
    updatedAt: "2024-11-23T15:00:00Z",
  },
  {
    id: "evt-008",
    title: "Victoria Falls Carnival",
    description: "Ring in the new year at Africa's greatest waterfall! Three days of music, culture, and adventure in the adrenaline capital of Africa.",
    category: "festival",
    date: "2024-12-29",
    time: "14:00",
    venue: "Victoria Falls Recreation Ground",
    city: "Victoria Falls",
    image: "/events/vic-falls-carnival.jpg",
    gallery: [],
    organizerId: "org-008",
    organizerName: "Vic Falls Carnival Ltd",
    ticketTypes: [
      { id: "tt-020", name: "Day Pass", description: "Single day entry", price: 50, currency: "USD", quantity: 2000, sold: 1200 },
      { id: "tt-021", name: "Full Festival", description: "3-day access", price: 120, currency: "USD", quantity: 1000, sold: 650 },
      { id: "tt-022", name: "VIP Experience", description: "All access + backstage", price: 300, currency: "USD", quantity: 100, sold: 75 },
    ],
    totalTickets: 3100,
    soldTickets: 1925,
    status: "published",
    createdAt: "2024-09-01T10:00:00Z",
    updatedAt: "2024-11-26T12:00:00Z",
  },
  {
    id: "evt-009",
    title: "Test Event - 1 Cent Ticket",
    description: "Testing event with 1 cent ticket for payment verification",
    date: "2024-12-25",
    time: "14:00",
    venue: "Online Test",
    city: "Virtual",
    organizerId: "org-001",
    organizerName: "Ghettocracy Entertainment",
    ticketTypes: [
      { id: "tt-023", name: "Test Ticket", description: "1 cent test ticket for payment verification", price: 0.01, currency: "USD", quantity: 1000, sold: 0 },
    ],
    totalTickets: 1000,
    soldTickets: 0,
    category: "other",
    image: "/events/test-event.jpg",
    status: "published",
    createdAt: "2024-11-27T10:00:00Z",
    updatedAt: "2024-11-27T10:00:00Z",
  },
];

export const mockOrganizers: Organizer[] = [
  {
    id: "org-001",
    name: "Ghettocracy Entertainment",
    email: "info@ghettocracy.co.zw",
    phone: "+263773909307",
    company: "Ghettocracy Entertainment",
    verified: true,
    totalEvents: 12,
    totalRevenue: 45000,
    pendingPayout: 2500,
    joinedAt: "2023-06-15T10:00:00Z",
  },
  {
    id: "org-002",
    name: "Zimbabwe Athletics Association",
    email: "events@zaa.co.zw",
    phone: "+263773909307",
    company: "Zimbabwe Athletics Association",
    verified: true,
    totalEvents: 8,
    totalRevenue: 78000,
    pendingPayout: 5600,
    joinedAt: "2022-01-10T08:00:00Z",
  },
];

export const mockBanners: Banner[] = [
  {
    id: "ban-001",
    type: "hero",
    position: 1,
    image: "",
    link: "/events/evt-001",
    title: "Ghettocracy Comedy Night - Get Your Tickets Now!",
    organizerId: "org-001",
    startDate: "2024-11-01",
    endDate: "2024-12-15",
    pricePerDay: 20,
    status: "available",
  },
  {
    id: "ban-002",
    type: "hero",
    position: 2,
    image: "",
    link: "/events/evt-003",
    title: "Jah Prayzah Live - Don't Miss Out!",
    organizerId: "org-003",
    startDate: "2024-11-15",
    endDate: "2024-12-22",
    pricePerDay: 20,
    status: "available",
  },
  {
    id: "ban-003",
    type: "hero",
    position: 3,
    image: "",
    link: "",
    title: "",
    pricePerDay: 20,
    status: "available",
  },
  {
    id: "ban-004",
    type: "hero",
    position: 4,
    image: "",
    link: "",
    title: "",
    pricePerDay: 20,
    status: "available",
  },
  {
    id: "ban-005",
    type: "hero",
    position: 5,
    image: "",
    link: "",
    title: "",
    pricePerDay: 20,
    status: "available",
  },
  {
    id: "ban-section-001",
    type: "section",
    position: 1,
    image: "",
    link: "",
    title: "",
    pricePerDay: 10,
    status: "available",
  },
  {
    id: "ban-section-002",
    type: "section",
    position: 2,
    image: "",
    link: "",
    title: "",
    pricePerDay: 10,
    status: "available",
  },
  {
    id: "ban-section-003",
    type: "section",
    position: 3,
    image: "",
    link: "",
    title: "",
    pricePerDay: 10,
    status: "available",
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "tkt-001",
    eventId: "evt-001",
    ticketTypeId: "tt-001",
    ticketTypeName: "Mbombera",
    eventTitle: "Ghettocracy Comedy Night 2024",
    eventDate: "2024-12-15",
    eventTime: "19:00",
    venue: "Harare International Conference Centre",
    buyerName: "Tatenda Moyo",
    buyerContact: "+263771234567",
    buyerDisplayName: "Tate M.",
    price: 15,
    markup: 0,
    totalPaid: 16.50,
    currency: "USD",
    paymentMethod: "ecocash",
    paymentStatus: "completed",
    qrCode: "ETKT-001-GHT24-MB-TM",
    validated: false,
    isAdmitted: false,
    purchasedAt: "2024-11-20T14:30:00Z",
    saleType: "online",
  },
  {
    id: "tkt-002",
    eventId: "evt-001",
    ticketTypeId: "tt-002",
    ticketTypeName: "VIP",
    eventTitle: "Ghettocracy Comedy Night 2024",
    eventDate: "2024-12-15",
    eventTime: "19:00",
    venue: "Harare International Conference Centre",
    buyerName: "Chiedza Banda",
    buyerContact: "+263772345678",
    buyerDisplayName: "Chi B.",
    price: 50,
    markup: 5,
    totalPaid: 60.50,
    currency: "USD",
    paymentMethod: "visa",
    paymentStatus: "completed",
    qrCode: "ETKT-002-GHT24-VIP-CB",
    validated: true,
    validatedAt: "2024-12-15T18:45:00Z",
    validatedBy: "staff-001",
    isAdmitted: true,
    admittedAt: "2024-12-15T18:45:00Z",
    admittedBy: "staff-001",
    purchasedAt: "2024-11-18T09:15:00Z",
    saleType: "online",
  },
  {
    id: "tkt-003",
    eventId: "evt-001",
    ticketTypeId: "tt-001",
    ticketTypeName: "Mbombera",
    eventTitle: "Ghettocracy Comedy Night 2024",
    eventDate: "2024-12-15",
    eventTime: "19:00",
    venue: "Harare International Conference Centre",
    buyerName: "John Doe",
    buyerContact: "+263773456789",
    buyerDisplayName: "Anonymous",
    price: 15,
    markup: 0,
    totalPaid: 15,
    currency: "USD",
    paymentMethod: "cash",
    paymentStatus: "completed",
    qrCode: "ETKT-003-GHT24-MB-JD",
    validated: false,
    isAdmitted: false,
    purchasedAt: "2024-12-15T17:30:00Z",
    saleType: "gate",
  },
];

export const mockStaffMembers: StaffMember[] = [
  {
    id: "staff-001",
    organizerId: "org-001",
    name: "Tendai Nyamande",
    email: "tendai@ghettocracy.co.zw",
    phone: "+263771111111",
    role: "gate_manager",
    assignedEvents: ["evt-001", "evt-006"],
    isActive: true,
    createdAt: "2024-10-01T08:00:00Z",
  },
  {
    id: "staff-002",
    organizerId: "org-001",
    name: "Sarah Mukwena",
    email: "sarah@ghettocracy.co.zw",
    phone: "+263772222222",
    role: "ticket_seller",
    assignedEvents: ["evt-001"],
    isActive: true,
    createdAt: "2024-10-15T09:00:00Z",
  },
];

export const mockPayoutRequests: PayoutRequest[] = [
  {
    id: "payout-001",
    organizerId: "org-001",
    organizerName: "Ghettocracy Entertainment",
    amount: 500,
    currency: "USD",
    status: "approved",
    requestedAt: "2024-11-01T10:00:00Z",
    processedAt: "2024-11-03T14:30:00Z",
    processedBy: "admin",
    paymentMethod: "Bank Transfer",
    paymentDetails: "CBZ Bank - 1234567890",
    transactionCost: 2,
  },
  {
    id: "payout-002",
    organizerId: "org-001",
    organizerName: "Ghettocracy Entertainment",
    amount: 750,
    currency: "USD",
    status: "pending",
    requestedAt: "2024-11-25T11:00:00Z",
    paymentMethod: "EcoCash",
    paymentDetails: "+263773909307",
    transactionCost: 2,
  },
  {
    id: "payout-003",
    organizerId: "org-002",
    organizerName: "Zimbabwe Athletics Association",
    amount: 1200,
    currency: "USD",
    status: "processing",
    requestedAt: "2024-11-20T09:00:00Z",
    paymentMethod: "Bank Transfer",
    paymentDetails: "Stanbic Bank - 0987654321",
    transactionCost: 2,
  },
];

export function getEventsByCategory(category: string): Event[] {
  if (category === "all") return mockEvents.filter((e) => e.status === "published");
  return mockEvents.filter((e) => e.category === category && e.status === "published");
}

export function getEventById(id: string): Event | undefined {
  return mockEvents.find((e) => e.id === id);
}

export function getNewestEvents(count = 8): Event[] {
  return mockEvents
    .filter((e) => e.status === "published")
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())
    .slice(0, count);
}

export function getFeaturedEvents(): Event[] {
  return mockEvents
    .filter((e) => e.status === "published")
    .sort((a, b) => b.soldTickets - a.soldTickets)
    .slice(0, 4);
}

export function getUpcomingEvents(): Event[] {
  const now = new Date();
  return mockEvents
    .filter((e) => e.status === "published" && new Date(e.date) >= now)
    .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
}

export function getActiveBanners(type: "hero" | "section"): Banner[] {
  return mockBanners.filter((b) => b.type === type);
}

export function getTicketsByEvent(eventId: string): Ticket[] {
  return mockTickets.filter((t) => t.eventId === eventId);
}

export function getStaffByOrganizer(organizerId: string): StaffMember[] {
  return mockStaffMembers.filter((s) => s.organizerId === organizerId);
}

export function getPayoutsByOrganizer(organizerId: string): PayoutRequest[] {
  return mockPayoutRequests.filter((p) => p.organizerId === organizerId);
}

export const mockUsers: User[] = Object.values(demoUsers);
