// Zimbabwe locations — cities, towns, suburbs, growth points, villages.
// Sourced from OpenStreetMap (c) OpenStreetMap contributors, ODbL license,
// via the Overpass API. Pre-sorted city > town > suburb > village > hamlet
// > locality, so substring matches surface bigger places first.
export const ZIMBABWE_LOCATIONS: string[] = [
  "Harare",
  "Bulawayo",
  "Chitungwiza",
  "Mutare",
  "Gweru",
  "Kwekwe",
  "Kadoma",
  "Masvingo",
  "Epworth",
  "Wedza",
  "Chinhoyi",
  "Marondera",
  "Norton",
  "Chegutu",
  "Hwange",
  "Beitbridge",
  "Bindura",
  "Zvishavane",
  "Victoria Falls",
  "Redcliff",
  "Chiredzi",
  "Rusape",
  "Kariba",
  "Karoi",
  "Ruwa",
  "Gokwe",
  "Chipinge",
  "Shurugwi",
  "Gwanda",
  "Plumtree",
  "Shamva",
  "Banket",
  "Mvuma",
  "Nyanga",
  "Mhangura",
  "Sanyati",
  "Chimanimani",
  "Macheke",
  "West Nicholson",
  "Lupane",
  "Triangle",
  "Alaska",
  "Arcturus",
  "Arda Transau",
  "Binga",
  "Birchenough Bridge",
  "Buhera",
  "Centenary",
  "Chakari",
  "Checheche",
  "Chireya",
  "Chivhu",
  "Chivi",
  "Concession",
  "Dema",
  "Dete",
  "Eiffel Flats",
  "Empress Mine",
  "Filabusi",
  "Glendale",
  "Golden Valley",
  "Goromonzi",
  "Guruve",
  "Gutu",
  "Hauna",
  "Jerera",
  "Juru",
  "Kotwa",
  "Magunje",
  "Makuti",
  "Manhenga",
  "Mashumbi Pools",
  "Mberengwa",
  "Melfort",
  "Morgenster",
  "Mount Darwin",
  "Murambinda",
  "Murombedzi",
  "Mutasa",
  "Mutoko",
  "Muzarabani Township",
  "Mvurwi",
  "Ndolwane",
  "Nembudziya",
  "Neshuro",
  "Nkayi",
  "Nyabira",
  "Nyamapanda",
  "Nyanyadzi",
  "Nyazura",
  "Nyika Growth Point",
  "Sadza",
  "Siabuwa",
  "St Alberts",
  "Tsanzaguru",
  "Tsholotsho",
  "Turf Town",
  "Zhombe Joel",
  "Zimunya",
  "Amaveni",
  "Arundel",
  "Ascot",
  "Avondale",
  "Avondale West",
  "Barbour Fields",
  "Belvedere",
  "Bluff Hill",
  "Borrowdale",
  "Bradfield",
  "Braeside",
  "Brundish",
  "Budiriro",
  "Burnside",
  "Carrick Creagh Villas",
  "CBD",
  "Charter",
  "Cherima",
  "Chibondo",
  "Chicago",
  "Chikanga",
  "Chikonohono",
  "Chinamano",
  "Chinamano Extension",
  "Chipadze",
  "Chisipite",
  "Chitambo",
  "Chizhanje",
  "Cold Comfort",
  "Cold Stream",
  "Cowdray Park",
  "Cranborne",
  "Damofalls Park",
  "Denver Township",
  "Domboramwari",
  "Dzivarasekwa",
  "Dzivarasekwa Section 2",
  "Dzivarasekwa Section 3",
  "Eastlea",
  "Eastvale",
  "Emakhandeni",
  "Emganwini",
  "Emhlangeni",
  "Empress Mine Township",
  "Eyestone Park",
  "Federation",
  "Fernhill",
  "Fourwinds",
  "Gadzema",
  "Glen Forest",
  "Glen Norah",
  "Glen Norah A",
  "Glen Norah B",
  "Glen Norah C",
  "Glen View",
  "Glenwood",
  "Glenwood Park",
  "Greendale",
  "Greystone Park",
  "Gunhill",
  "Gwabalanda",
  "Hatcliffe",
  "Hatfield",
  "Highfield",
  "Highlands",
  "Hillside",
  "Hopley",
  "Hunyani",
  "Ilanda Gardens",
  "Impali Housing Estates",
  "Inyati Mine",
  "Jacaranda Suburbs",
  "Jacha",
  "Kambuzuma",
  "Katanda",
  "Kenilworth",
  "Khumalo",
  "Khwalu",
  "Killarney",
  "Kusile Flats",
  "Kuwadzana",
  "Kuwdzana Phase 3",
  "Lewisam",
  "Lochview",
  "Luveve",
  "Mabelreign",
  "Mabvuku",
  "Madamba",
  "Madinginye",
  "Madubes",
  "Magada",
  "Magwegwe",
  "Mahatshula",
  "Mahatshula East",
  "Mahatshula South",
  "Makokoba",
  "Makomo",
  "Makomo Extension",
  "Malindela",
  "Mandara",
  "Mapako",
  "Marlborough",
  "Matapi",
  "Matibe",
  "Mbare",
  "Mbizo",
  "Milayo",
  "Milton Park",
  "Mkoba",
  "Mkoba 14",
  "Mkoba 18",
  "Mkoba 19",
  "Mkoba 3",
  "Monavale",
  "Montrose",
  "Mopani Township",
  "Morningside",
  "Mount Pleasant",
  "Mpata",
  "Mpopoma",
  "Msasa Park",
  "Mshumavale",
  "Mtapa",
  "Mucheke",
  "Mufakose",
  "Muguta",
  "Muguta Extension",
  "Mzari",
  "Mzilikazi",
  "Njube",
  "Nketa",
  "Nketa 7",
  "Nkulumane",
  "Northend",
  "Northlea",
  "Northwood",
  "Nyamadzawo",
  "Nyamhuka",
  "Nyamhunga",
  "Nyikavanhu",
  "Orange Grove",
  "Overspill",
  "Parklands",
  "Parklands Extension",
  "Parkview",
  "Prospect",
  "Pumula",
  "Queens Park East",
  "Queens Park West",
  "Rhodene",
  "Rimuka",
  "Riverside",
  "Romney Park",
  "Rujeko",
  "Rusununguko",
  "Rutendo",
  "Rutendo Extension",
  "Ruvimbo",
  "Rydale Ridge",
  "Sakubva",
  "Saturday Retreat",
  "Sauerstown",
  "Seke",
  "Senga",
  "Sizinda",
  "Southdown",
  "Southlea Park",
  "Southview Park",
  "Spitzkop",
  "St. Mary's",
  "Stopover",
  "Strathaven",
  "Suburbs",
  "Sunnyside",
  "Tafara",
  "Tafara Township",
  "Tegela",
  "TelD - Tower",
  "The Grange",
  "Thorngrove",
  "Trust",
  "Tshabalala",
  "Tshidixhwa",
  "Tynwald",
  "Vainona",
  "Vengere",
  "Vhembe Heights",
  "Warren Park 1",
  "Warren Park D",
  "Waterfalls",
  "Waverly",
  "Westgate",
  "Westlea",
  "Westview",
  "Westwood",
  "White City",
  "Woodlands",
  "Zengeza",
  "Zimre Park",
  "Zinyengere",
  "Kamativi",
  "Mazowe",
  "Colleen Bawn",
  "Headlands",
  "Chirundu",
  "Msampa Fishing Village",
  "Avoca",
  "Bangure",
  "Bannochburn",
  "Baravara",
  "Battlefields",
  "Beacon Hill",
  "Beatrice",
  "Bee Mine",
  "Berejena Hosi Yorugare",
  "Betera",
  "Bhamala Business Center",
  "Bhamala Village",
  "Bharamasvesve Village",
  "Bhoki Village",
  "Bhutabubili",
  "Birdspring",
  "Blanket Mine",
  "Bromley",
  "Brunapeg",
  "Brunapeg Mission",
  "Buchwa",
  "Buvume Mission",
  "Bvute",
  "Cashel",
  "Cathleen",
  "Cement",
  "Chadereka Business Center- Muzarabani",
  "Chaka",
  "Chako",
  "Chakohwa",
  "Chambara",
  "Champagne",
  "Chamumnanga",
  "Charara",
  "Chaseyama",
  "Chatsworth",
  "Chibunje",
  "Chibuwe",
  "Chidamoyo",
  "Chigaro",
  "Chikombedzi",
  "Chikore Mission",
  "Chikutubwe Village 1",
  "Chikutubwe Village 2",
  "Chikutubwe Village 3",
  "Chikutubwe Village 4",
  "Chikutubwe Village 5",
  "Chikwanda Mission",
  "Chikwarakwara",
  "Chikwingwizha Seminary",
  "Chimbudzi",
  "Chimkomba",
  "Chinyanánya",
  "Chinyika",
  "Chinyudze",
  "Chipunha",
  "Chirozva",
  "Chitakatira Growth Point",
  "Chitowa Two Business Center",
  "Chitsiko Village",
  "Chiutsi Business Centre",
  "Chivaku",
  "Chusya",
  "Cross Dete",
  "Cross Mabale",
  "Cyrene",
  "Daiseyfield",
  "Dandawa",
  "Danga",
  "David Livingstone Mission",
  "Devure",
  "Dhibha Village",
  "Dimbiti",
  "Domboshava Mission",
  "Domboshawa",
  "Donain",
  "Donga",
  "Donjane Village",
  "Dorowa",
  "Dorset",
  "Dotibani",
  "Driefontein Mission",
  "Dumisa",
  "Emadramini",
  "Emakharadini eRanking",
  "Embakwe Mission",
  "Empandeni Mission",
  "Esibomvu",
  "Esigodini",
  "Fairfield",
  "Felixburg",
  "Figtree",
  "Fred Mine",
  "Gambisa",
  "Gambu",
  "Gandiwa Village",
  "Ganyungu",
  "Gaths Mine",
  "Glenclova",
  "Gokomere Mission",
  "Gorodema",
  "Grand Reef",
  "Gudyanga",
  "Guinea Fowl",
  "Gutu Mission",
  "Guyu",
  "Gwanika",
  "Gwenzi",
  "Gweshe",
  "Hande",
  "Hanke Mission",
  "Hideaways Nantwich Lodge",
  "Hippo Pools",
  "Holy Cross Mission",
  "Hombwe",
  "Homestead",
  "Hotsprings",
  "Hoya Business Center- Muzarabani",
  "Hwange Main Camp",
  "Imbizo Village",
  "Ingwizi",
  "Inyathi Mission",
  "Irisvale",
  "Jamba Business Centre",
  "James village 1",
  "James village 2",
  "James Village 3",
  "Jersey",
  "Jichidza Mission",
  "Jotsholo",
  "Junction Gate",
  "Kabidza Growth Point",
  "Kabuyuni Rural Service Center",
  "Kana Mission",
  "Kanhukamwe Village",
  "Kanyemba Village 5",
  "Kariyangwe",
  "Kasama",
  "Kasawi Village",
  "Kezi",
  "Khami Prison",
  "Kildonan",
  "King Mine",
  "Kombo",
  "Koodoovale",
  "Korodziba",
  "Kuma G",
  "Kutama",
  "Lalapansi",
  "Landsdowne",
  "Legion Mine",
  "Lions Den",
  "Lochard",
  "Lollies",
  "Lonely Mine",
  "Loreto Mission",
  "Lubimbi",
  "Lundi",
  "Lusulu",
  "Lutumba",
  "Machongwe",
  "Madadzi",
  "Magama Mission",
  "Mahlangu Village",
  "Mahogo Village \"A\"",
  "Mahogo Village \"B\"",
  "Mahusekwa",
  "Makona National Parks HQ",
  "Malipati",
  "Mamina",
  "Manama Mission",
  "Mangwarangwara Village",
  "Manhondo",
  "Manjolo",
  "Manyonho",
  "Manyoni",
  "Manyoni village 3",
  "Manyoni village 7",
  "Manyoni village 8",
  "Manyoni Village 9",
  "Manzamunyama Village",
  "Mapangwe",
  "Maphisa",
  "Mapolisa",
  "Mapula",
  "Maryland",
  "Masanga",
  "Masendu",
  "Mashava",
  "Mashingaidze",
  "Mashoko",
  "Mashongwe",
  "Masuwe",
  "Mataga",
  "Matara Village",
  "Matareke",
  "Mathanzima Village",
  "Matibi Mission",
  "Matizha Business Centre",
  "Mavaire",
  "Mawela Village",
  "Mawundi Village",
  "Mayfield Estate",
  "Mayisa Village",
  "Mazunga",
  "Mbalabala",
  "Mbembesi",
  "Mbondiya Village",
  "Mhakwe",
  "Mhandarume",
  "Mhasvi Village",
  "Mhokonye",
  "Mhondiwa Village",
  "Milverton",
  "Mnene Mission",
  "Monef",
  "Mount Belingwe",
  "Mount Selinda Mission",
  "Moyomusante Mission",
  "Mpinga",
  "Mpumelelo",
  "Msuna",
  "Mubaira",
  "Mubereki Village",
  "Mukaro Mission",
  "Munyanyi",
  "Munyati",
  "Munyati St Peter's Business Centre",
  "Munyoro Township",
  "Mupora Village",
  "Murape",
  "Murawi",
  "Muromo",
  "Mushangi Business Center",
  "Mushipe",
  "Musingira",
  "Musume Mission",
  "Mutambara Mission",
  "Mutema",
  "Mutero Mission",
  "Mutiusinazita",
  "Mutorashanga",
  "Mutsaka",
  "Muzokomba",
  "Muzvezve II, Village 13",
  "Mwami",
  "Mwemba",
  "Mwenezi",
  "Mzizi Village",
  "Navata Village",
  "Ndebele Village",
  "Ndumo Village",
  "Nemanwa Growth Point",
  "Nemauku",
  "Nenowhe",
  "Nenyunka",
  "Nerupiri",
  "Neshava",
  "Ngamo",
  "Ngomahuru",
  "Ngundu",
  "Ngwende",
  "Ngwenya Mission",
  "Nhedziwa",
  "Ntabazinduna",
  "Nyahowe Business Centre",
  "Nyamandhlovu",
  "Nyamaropa",
  "Nyamuzizi Business Center-Mutoko",
  "Nyashanu Mission",
  "Nzama Mahogo Village",
  "Odzi",
  "Old Mutare",
  "Pa Cross",
  "Pagati",
  "Pakame Mission",
  "Pangani",
  "Paraffin Village",
  "Pashu",
  "Penhalonga",
  "Piki Village",
  "Prison Camp",
  "Queens Mine",
  "Raditladi",
  "Robins Camp",
  "Rufaro Mission",
  "Rutenga",
  "Saba",
  "Samambwa Village",
  "Sandura Township",
  "Sawmills",
  "Selemwe Village-Nyaminyami",
  "Selous",
  "Sengezi Village",
  "Senkwasi Village",
  "Serima Mission",
  "Shangani",
  "Shangani Mine",
  "Shinja",
  "Shinje Township",
  "Siakobvu",
  "Sidakeni Business Center",
  "Silobela",
  "Silveira Mission",
  "Silver Star village 1",
  "Silver Star village 2",
  "Simangani",
  "Sinamatella Camp",
  "Sitsha Village",
  "Sosombe II Village 2",
  "St Joseph's Mission",
  "St. Patricks",
  "St.George Business Center",
  "Stanmore",
  "Supa",
  "Svisvi Business Centre",
  "Tanganda Halt",
  "Tangwena",
  "Tchoda",
  "Tegwani Training Institute",
  "Tengwe",
  "Tiger Reef",
  "Tombo",
  "Tongogara Refugee Camp",
  "Totororo Business Center",
  "Troutbeck",
  "Tshelanyemba Salvation Army Mission",
  "Tsungwezi",
  "Turf Village 3",
  "Turk Mine",
  "Tuzuka",
  "Ultra Area",
  "Vanguard Mine",
  "Venice",
  "Village",
  "Viriri",
  "Vubachikwe Mine",
  "Watsomba",
  "Wengezi",
  "Wilda",
  "Willoughby",
  "Windsor",
  "Yorks",
  "Zaka",
  "Zamchiya",
  "Zezani Mission",
  "Zhomba Business Centre",
  "Zhombe Joel Center",
  "Zhombe Mission Township",
  "Zikamanus",
  "Zin'anga",
  "Zomba",
  "Zumbara",
  "Zvabagwamba",
  "Zvenyika Village",
  "Zvipani Business Center",
  "Ndola",
  "Baswi",
  "Bradza",
  "Chabumbulukwa",
  "Chakaza",
  "Chawatama",
  "Chezya",
  "Chieza",
  "Chifadza",
  "Chikuri",
  "Chikwizi",
  "Chimenga",
  "Chingonya",
  "Chinyanga",
  "Chinzou",
  "Chipwanyira",
  "Chirinda",
  "Chiurwi",
  "Chizimo",
  "Choto-Nyasha",
  "Chunga",
  "Dirikwe",
  "Dombo",
  "Dzaibva",
  "Dzapasi",
  "Fadzamoyo",
  "Fort Rixon",
  "Fulunga",
  "Ganyo",
  "Garawaziva",
  "Gotora",
  "Gudo",
  "Gwaay",
  "Hambira",
  "Hatinahama",
  "Hodero",
  "Hunts Road Halt",
  "Hwali",
  "Indiva",
  "Ingusi",
  "Insiza",
  "Jongwe",
  "Kabila",
  "Kalowa",
  "Kandenga",
  "Kasase",
  "Kenjobo",
  "Kings Camp Fishing Village",
  "Kwarire",
  "Lancaster",
  "Lukosi",
  "Lusumbuko Busines Centre",
  "Mabvuregudo",
  "Machacha",
  "Madambi",
  "Madume",
  "Madya",
  "Madzivire",
  "Magondo-Mabvuregudo",
  "Mahembe",
  "Makarara",
  "Makwa",
  "Mampata",
  "Mangoma",
  "Manhuru",
  "Manjengwa",
  "Manzinde",
  "Mapfumo",
  "Mapfungautsi",
  "Maradzano",
  "Martin Spur",
  "Masasa",
  "Masenda",
  "Mashandu",
  "Mashinya",
  "Mashinyanga",
  "Masocha",
  "Masoro Turnoff Township",
  "Mataswa",
  "Matendere",
  "Matiashe",
  "Matingo",
  "Matombomaviri",
  "Matshiloni",
  "Maweni",
  "Mawire",
  "Mazhero village",
  "Mbavara",
  "Melsetter Junction",
  "Mhaka",
  "Mhizha",
  "Mpudzi",
  "Msuna Hills",
  "Mubvirwi",
  "Muchuchu",
  "Muchuweni",
  "Mudanda",
  "Mudawose",
  "Mudinzwa",
  "Mukono",
  "Mukutukutu",
  "Mumbijo",
  "Mumera",
  "Mupambe",
  "Murairwa",
  "Murari",
  "Musendeki",
  "Mushongwe",
  "Musikavanhu",
  "Mutauto",
  "Mutawurwa",
  "Mutengezi Farm",
  "Muziti",
  "Mwangazi",
  "Mwarutsa",
  "Myrlen Farm",
  "Ndanga Business Centre",
  "Nechitima",
  "Nemaramba",
  "Nemutenzi",
  "Neshire",
  "Njarima",
  "Nkandebwe",
  "PaKeny",
  "Rukweza",
  "Rupfunde",
  "Sabi Bridge",
  "Sango",
  "Saruwaka - Gowa",
  "Siamusale",
  "Siamwinde",
  "Sichimvwali",
  "Sosombe II Ext Village 10",
  "Sosombe II Ext Village 11",
  "Sosombe II Ext Village 12",
  "Sosombe II Ext Village 13",
  "Sosombe II Ext Village 7",
  "Sosombe II Ext Village 8",
  "Sosombe II Ext Village 9",
  "Sosombe II Village 1",
  "Sosombe II Village 3",
  "Sosombe II Village 4",
  "Sosombe II Village 5",
  "Svenge-Mabvuregudo",
  "Svova",
  "Swanscoe",
  "Takaengwa",
  "Tonhorai",
  "Towla",
  "Tuli ZRP",
  "Utete",
  "Wadzenenga",
  "Watekama",
  "Zimunda",
  "Zona",
  "Zvavamwena",
  "Zvipiripiri",
  "Zvokuitirwa",
  "Broken Bridge",
  "Buffalo Bend",
  "Chemankunguwo",
  "Chikarudzo Business centre",
  "Copper Queen",
  "Dzivanini Mud Flats",
  "Gomo Dam",
  "Gonzoni",
  "Hertfordshire Phase 1 residential",
  "Mapfungwe",
  "Masoka",
  "Mindora Resettlement",
  "Mudzonga Village",
  "Munonde Water Holes",
  "Musnago Boundary point",
  "Shawa Quarry",
  "Silalatshani Irrigation Scheme",
  "The Hill",
  "The Ridge",
  "The Valley"
];
